language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly
sudo: false
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
install:
  - travis_retry composer install --no-interaction
script:
  - ./vendor/bin/phpunit
